USE customer_behavior;
SELECT * FROM customer_behavior.customer_data limit 5;

# Q1: What is the total revenue generated by male vs female customers?
USE customer_behavior;

SELECT 
    Gender,
    SUM(`Purchase Amount (USD)`) AS Total_Revenue
FROM 
    customer_data
GROUP BY 
    Gender;

# Q2 which customer used a discount but still spent more than the average purchase amount
select (`Customer ID`), (`Purchase Amount (USD)`)
FROM   customer_data
where (`Discount Applied`) = "yes" and (`Purchase Amount (USD)`) >(select AVG((`Purchase Amount (USD)`) )FROM customer_data );


# Q3 what are the top 5 products  with highest average review

SELECT (`Item Purchased`), round( AVG((`Review Rating`) ),2) as "Average product rating"
from customer_data
group by (`Item Purchased`)
order by  AVG((`Review Rating`) ) desc 
limit 5;


-- Q4 cmp the avg purchase amount between standard and express shipping
select (`shipping Type`) ,
round(  AVG((`Purchase Amount (USD)`) ) ,2)
from customer_data
where (`shipping Type`) in ("Standard","Express")
group by (`shipping Type`);


-- Q5 do subscribe customer spend more  ? compare avg and total revenue between subs and non-subs.

select (`Subscription Status`),
COUNT((`Customer ID`)) as Total_customers,
round(  AVG((`Purchase Amount (USD)`) ) ,2) as Avg_spend,
 round( SUM((`Purchase Amount (USD)`)) ,2) as Total_Revenue
 from customer_data
 group by  (`Subscription Status`)
 order by Total_Revenue, Avg_spend desc;
 
 
 #Q6 which 5 product have highest % of purchase with discount
 
 select (`Item Purchased`), 
 round( SUM(CASE WHEN (`Discount Applied`) = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100 ,2) as discount_rate
  from customer_data
  group by (`Item Purchased`)
  order by discount_rate desc
  limit 5;
 
 #Q7 segement customer into new returning and loyal based on thier total number od previous purchase , and show the count of each segment
 with customer_type as (
 select (`Customer ID`),(`Previous Purchases`),
 CASE
	WHEN (`Previous Purchases`) = 1 THEN 'NEW'
    WHEN (`Previous Purchases`) between 2 and 10  THEN 'Returning'
    ELSE 'Loyal'
	END as customer_segment
from customer_data
 )
 select customer_segment, count(*) as "Number of Customers"
 from customer_type
 group by customer_segment;
 
 
 #Q8 what are the 3 top most purchsed product with each category
 with Item_counts  as (
 select Category, (`Item Purchased`),
 count((`Customer ID`)) as total_order,
 ROW_NUMBER() over(partition by Category order by count((`Customer ID`)) desc) as Item_rank
 from customer_data
 group by Category, (`Item Purchased`)
 )
 select Item_rank, Category, (`Item Purchased`), total_order 
 from Item_counts
 where Item_rank <= 3;
 
 
 
 
 
 
 
 